# Generated by Django 3.2 on 2022-01-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_user_id_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'admin'), (2, 'contable'), (3, 'terminal')], default=0, null=True, verbose_name='Rol'),
        ),
    ]
