# Generated by Django 3.2 on 2022-03-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'dummy'), (1, 'admin'), (2, 'contable'), (3, 'terminal')], default=0, null=True, verbose_name='Rol'),
        ),
    ]
