# Generated by Django 3.2 on 2021-05-01 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['nombre']},
        ),
    ]
