# Generated by Django 3.2 on 2021-05-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210501_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiones',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='regiones',
            name='capital',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
