# Generated by Django 3.2 on 2021-05-01 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_regiones_abreviatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regiones',
            options={'ordering': ['id']},
        ),
    ]
