# Generated by Django 3.2 on 2021-10-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_terminales'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminales',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
