# Generated by Django 3.2 on 2021-10-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_terminales_direccion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Terminales',
            new_name='Sucursal',
        ),
    ]
