# Generated by Django 3.2 on 2021-10-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211026_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comunas',
            new_name='Comuna',
        ),
        migrations.RenameModel(
            old_name='Provincias',
            new_name='Provincia',
        ),
    ]
