# Generated by Django 3.2 on 2021-11-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211027_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Sucursal Activa'),
        ),
    ]
