# Generated by Django 3.2 on 2021-11-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_sucursal_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='es_terminal',
            field=models.BooleanField(default=False, verbose_name='Sucursal es terminal'),
        ),
    ]
