# Generated by Django 3.2 on 2022-03-04 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entregado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Rendición')),
                ('pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Rendición')),
                ('arqueo', models.JSONField(verbose_name='Arqueo de Billetes')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Nombre Contador')),
            ],
        ),
        migrations.AddField(
            model_name='rendicion_cuentas',
            name='id_recepcion_cuentas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.recepcioncuentas', verbose_name='Cuenta Recepcionada'),
        ),
    ]
