# Generated by Django 3.2 on 2021-05-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='t_salida',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Collao'), (2, 'Lota'), (3, 'Arauco')], default=1, verbose_name='Terminal Salida'),
        ),
    ]
