# Generated by Django 3.2 on 2021-05-03 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_vehiculos_t_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='ano',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='nro',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nro Interno'),
        ),
    ]
