# Generated by Django 3.2 on 2021-05-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_auto_20210503_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Vehiculo Activo'),
        ),
    ]
