# Generated by Django 3.2 on 2021-09-20 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propietarios', '0001_initial'),
        ('buses', '0004_vehiculos_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='propietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='propietarios.propietarios'),
        ),
    ]
