# Generated by Django 3.2 on 2021-10-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0005_vehiculos_propietario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculos',
            old_name='activo',
            new_name='es_activo',
        ),
        migrations.RenameField(
            model_name='vehiculos',
            old_name='propietario',
            new_name='id_propietario',
        ),
    ]
