# Generated by Django 3.2 on 2021-10-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propietarios', '0001_initial'),
        ('recorridos', '0001_initial'),
        ('buses', '0006_auto_20211021_1307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehiculos',
            new_name='Vehiculo',
        ),
    ]
