# Generated by Django 3.2 on 2021-10-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0007_rename_vehiculos_vehiculo'),
        ('propietarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Propietarios',
            new_name='Propietario',
        ),
    ]
