# Generated by Django 3.2 on 2021-11-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0002_rename_recorrido_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='fecha_despacho',
            field=models.DateField(default='1999-01-01', verbose_name='Fecha Despacho'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='fecha_planilla',
            field=models.DateField(default='1999-01-01', verbose_name='Fecha de Planilla'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='hora_llegada',
            field=models.TimeField(blank=True, verbose_name='Hora llegada'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='hora_salida',
            field=models.TimeField(verbose_name='Hora salida'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
