# Generated by Django 3.2 on 2021-11-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0003_auto_20211103_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago_planilla',
            name='pagada',
            field=models.BooleanField(default=False, verbose_name='Planilla Pagada'),
        ),
    ]
