# Generated by Django 3.2 on 2021-11-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0004_pago_planilla_pagada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='hora_llegada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora llegada'),
        ),
    ]
