# Generated by Django 3.2 on 2021-11-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0008_auto_20211125_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='id_planilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recorridos.planilla', verbose_name='Planilla'),
        ),
    ]
