# Generated by Django 3.2 on 2021-11-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0009_alter_despacho_id_planilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='revalidada',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Planilla revalidada'),
        ),
    ]
