# Generated by Django 3.2 on 2021-11-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0010_alter_planilla_revalidada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='id_pago_planilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recorridos.pago_planilla'),
        ),
    ]
