# Generated by Django 3.2 on 2021-11-25 16:42
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0011_alter_planilla_id_pago_planilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='tiempo',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Duracion del Servicio'),
        ),
    ]
