# Generated by Django 3.2 on 2022-01-06 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0013_auxiliar_foto'),
        ('recorridos', '0013_alter_servicio_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='id_auxiliar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='conductores.auxiliar', verbose_name='Auxiliar'),
        ),
    ]
