# Generated by Django 3.2 on 2022-01-17 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('recorridos', '0014_alter_despacho_id_auxiliar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago_planilla',
            name='id_rendicion_cuentas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.rendicion_cuentas'),
        ),
    ]
