# Generated by Django 3.2 on 2021-05-01 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comunas_provincias_regiones'),
        ('conductores', '0002_conductores_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductores',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.comunas'),
        ),
        migrations.AlterField(
            model_name='conductores',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.regiones'),
        ),
    ]
