# Generated by Django 3.2 on 2021-05-01 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0003_auto_20210501_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductores',
            name='region',
        ),
    ]
