# Generated by Django 3.2 on 2021-05-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0004_remove_conductores_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductores',
            name='comuna',
            field=models.IntegerField(),
        ),
    ]
