# Generated by Django 3.2 on 2021-05-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0005_alter_conductores_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductores',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Conductor Activo'),
        ),
    ]
