# Generated by Django 3.2 on 2021-08-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0006_conductores_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductores',
            name='region',
            field=models.CharField(default=0, max_length=4, verbose_name='Region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conductores',
            name='comuna',
            field=models.CharField(max_length=4, verbose_name='Comuna'),
        ),
    ]
