# Generated by Django 3.2 on 2021-08-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0007_auto_20210830_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductores',
            name='comuna',
            field=models.IntegerField(verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='conductores',
            name='region',
            field=models.IntegerField(verbose_name='Region'),
        ),
    ]
