# Generated by Django 3.2 on 2021-09-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0008_auto_20210830_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductores',
            name='comuna',
            field=models.CharField(max_length=50, verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='conductores',
            name='region',
            field=models.CharField(max_length=50, verbose_name='Region'),
        ),
    ]
