# Generated by Django 3.2 on 2021-09-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0009_auto_20210903_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductores',
            name='comuna',
            field=models.IntegerField(verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='conductores',
            name='region',
            field=models.IntegerField(verbose_name='Region'),
        ),
    ]
