# Generated by Django 3.2 on 2021-11-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0012_rename_conductores_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxiliar',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_auxiliares'),
        ),
    ]
